// Projeto - Piscar LED
int pinoLed = 11;//Atribui o valor 9 a variável inteira ledPin, que irá representar o pino digital 9

void setup() {
    pinMode(pinoLed, OUTPUT);//Define ledPin (pino 9) como saída
}

void loop() {
    analogWrite(pinoLed, 5);
    delay(100);
    analogWrite(pinoLed, 50);
    delay(50);
    analogWrite(pinoLed, 100);
    delay(10);
    analogWrite(pinoLed, 150);
    delay(50);
    analogWrite(pinoLed, 200);
    delay(50);
    analogWrite(pinoLed, 255);
    delay(50);
    analogWrite(pinoLed, 300);
    delay(5000);
    analogWrite(pinoLed, 10);
    delay(10);
    analogWrite(pinoLed, 20);
    delay(50);
    analogWrite(pinoLed, 50);
    delay(50);
    analogWrite(pinoLed, 400);
    delay(50);
    analogWrite(pinoLed, 5);
    delay(100);
    analogWrite(pinoLed, 50);
    delay(50);
    analogWrite(pinoLed, 100);
    delay(10);
    analogWrite(pinoLed, 150);
    delay(50);
    analogWrite(pinoLed, 200);
    delay(50);
    analogWrite(pinoLed, 255);
    delay(50);
    analogWrite(pinoLed, 300);
    analogWrite(pinoLed, 5);
    delay(100);
    analogWrite(pinoLed, 50);
    delay(50);
    analogWrite(pinoLed, 100);
    delay(10);
    analogWrite(pinoLed, 150);
    delay(50);
    analogWrite(pinoLed, 200);
    delay(50);
    analogWrite(pinoLed, 255);
    delay(50);
    analogWrite(pinoLed, 300);
    analogWrite(pinoLed, 5);
    delay(100);
    analogWrite(pinoLed, 50);
    delay(50);
    analogWrite(pinoLed, 100);
    delay(10);
    analogWrite(pinoLed, 150);
    delay(50);
    analogWrite(pinoLed, 200);
    delay(50);
    analogWrite(pinoLed, 255);
    delay(50);
    analogWrite(pinoLed, 300);
    analogWrite(pinoLed, 5);
    delay(100);
    analogWrite(pinoLed, 50);
    delay(50);
    analogWrite(pinoLed, 100);
    delay(10);
    analogWrite(pinoLed, 150);
    delay(50);
    analogWrite(pinoLed, 200);
    delay(50);
    analogWrite(pinoLed, 255);
    delay(50);
    analogWrite(pinoLed, 300);
    analogWrite(pinoLed, 5);
    delay(100);
    analogWrite(pinoLed, 50);
    delay(50);
    analogWrite(pinoLed, 100);
    delay(10);
    analogWrite(pinoLed, 150);
    delay(50);
    analogWrite(pinoLed, 200);
    delay(50);
    analogWrite(pinoLed, 255);
    delay(50);
    analogWrite(pinoLed, 300);
    analogWrite(pinoLed, 5);
    delay(100);
    analogWrite(pinoLed, 50);
    delay(50);
    analogWrite(pinoLed, 100);
    delay(10);
    analogWrite(pinoLed, 150);
    delay(50);
    analogWrite(pinoLed, 200);
    delay(50);
    analogWrite(pinoLed, 255);
    delay(50);
    analogWrite(pinoLed, 300);
    analogWrite(pinoLed, 5);
    delay(100);
    analogWrite(pinoLed, 50);
    delay(50);
    analogWrite(pinoLed, 100);
    delay(10);
    analogWrite(pinoLed, 150);
    delay(50);
    analogWrite(pinoLed, 200);
    delay(50);
    analogWrite(pinoLed, 255);
    delay(50);
    analogWrite(pinoLed, 300);
    analogWrite(pinoLed, 5);
    delay(100);
    analogWrite(pinoLed, 50);
    delay(50);
    analogWrite(pinoLed, 100);
    delay(10);
    analogWrite(pinoLed, 150);
    delay(50);
    analogWrite(pinoLed, 200);
    delay(50);
    analogWrite(pinoLed, 255);
    delay(50);
    analogWrite(pinoLed, 300);
    analogWrite(pinoLed, 5);
    delay(100);
    analogWrite(pinoLed, 50);
    delay(50);
    analogWrite(pinoLed, 100);
    delay(10);
    analogWrite(pinoLed, 150);
    delay(50);
    analogWrite(pinoLed, 200);
    delay(50);
    analogWrite(pinoLed, 255);
    delay(50);
    analogWrite(pinoLed, 300);
    analogWrite(pinoLed, 5);
    delay(100);
    analogWrite(pinoLed, 50);
    delay(50);
    analogWrite(pinoLed, 100);
    delay(10);
    analogWrite(pinoLed, 150);
    delay(50);
    analogWrite(pinoLed, 200);
    delay(50);
    analogWrite(pinoLed, 255);
    delay(50);
    analogWrite(pinoLed, 300);
    analogWrite(pinoLed, 5);
    delay(100);
    analogWrite(pinoLed, 50);
    delay(50);
    analogWrite(pinoLed, 100);
    delay(10);
    analogWrite(pinoLed, 150);
    delay(50);
    analogWrite(pinoLed, 200);
    delay(50);
    analogWrite(pinoLed, 255);
    delay(50);
    analogWrite(pinoLed, 300);
    analogWrite(pinoLed, 5);
    delay(100);
    analogWrite(pinoLed, 50);
    delay(50);
    analogWrite(pinoLed, 100);
    delay(10);
    analogWrite(pinoLed, 150);
    delay(50);
    analogWrite(pinoLed, 200);
    delay(50);
    analogWrite(pinoLed, 255);
    delay(50);
    analogWrite(pinoLed, 300);
    
}





